server.port=8087
server.address=0.0.0.0

# MinIO Configuration
minio.server.url=http://minio:9000
minio.server.access-key=miniadmin
minio.server.secret-key=miniadmin123
minio.server.bucket-name=road-traffic-files

# Multipart file upload configuration
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Eureka Client Configuration
eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health,info
