server.port=8084

# MinIO Configuration
minio.server.url=http://roadtraffic-minio:9000
minio.server.access-key=miniadmin
minio.server.secret-key=miniadmin123
minio.server.bucket-name=captures
minio.server.public-url=http://51.195.11.201:7004


# Kafka Configuration
spring.kafka.bootstrap-servers=kafka:9092

# Eureka Client Configuration
eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB