# Server port
server.port=8083

# Kafka Consumer Configuration
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# Trust the package of the incoming DTO from verification-service
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.common.dto

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# DataSource Configuration
spring.datasource.url=jdbc:postgresql://postgres:5432/infractions_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Infraction Service URL (pour le client Feign)
infraction.service.url=http://infraction-service:8083
